### PR TITLE
add simple test_set_*** testcase in version_set

### PR DESCRIPTION
**Pull request by AliceLanniste**

### CODE REVIEW

**Comment by Fullstop000** [comment]
Pls run a `cargo fmt`

**Comment by AliceLanniste** [comment]
I think there is a bug in`version/mod.rs`  , when `right=mid` and `left < right`,the `while` loop will still running
```
pub fn find_file{
.....
 while left < right {
            let mid = left + right / 2;
            let f = &files[mid];
            if icmp.compare(f.largest.data(), ikey.as_slice()) == CmpOrdering::Less {
             
                left = mid + 1;
            } else {
            
                right = mid;
            }
}
```

**Comment by Fullstop000** [comment]
I forgot adding the parentness brackets 😂. It should be `(left + right) / 2`. Could you please fix it in this PR?
@AliceLanniste

**Comment by AliceLanniste** [comment]
I think the parentness brackets added,it seems like the `find_file`output is wrong,when `target ==mid.largest`,the output won't return ,I will try fix it

**Comment by Fullstop000** [comment]
I believe that the binary search in `find_file` should work fine after reading that part of the codes carefully. When `files[mid].largest == target", the loop will continue reducing `right` or increasing left util `left >= right`. 
But I just simulate some situations roughly on my draft. It'll be very appreciated for me if you can establish a robust testing case for it.

**Comment by Fullstop000** [comment]
What's your rust toolchain version? @AliceLanniste

**Comment by AliceLanniste** [comment]
rustc 1.35.0

**Comment by Fullstop000** [comment]
I added a `rust-toolchain` to specify a stable toolchain version `1.38.0`. If this not works, maybe you could just delete that empty line :).

**Pull request merged**
