### PR TITLE
support inline skiplist

### PR DESCRIPTION
**Pull request by accelsao**

### CODE REVIEW

**Comment by accelsao** [comment]
@Fullstop000 Maybe you can open a new PR for an offset-based arena and its tests.

**Comment by Fullstop000** [comment]
@accelsao Concurrent tests are failed due to invalid memory ref. And I've tested them with gdb and Valgrind but didn't found the clause. PTAL if you have time :)

**Comment by Fullstop000** [comment]
@accelsao I think I might find the root cause of UB:
In previous implementation, when allocating a `Node`, we init the `next_nodes` by calling `ptr::write_bytes`
```rust
ptr::write_bytes(&mut (*p).next_nodes, 0, height);
```
which writes `height` * `size_of::<[AtomicPtr<Node>; MAX_HEIGHT]>()` bytes. Just a huge mistake 😂.

Instead, we should use:
```rust
ptr::write_bytes((&mut (*p)).next_nodes.as_mut_ptr(), 0, height);
```
which correctly writes `height` * `size_of::<AtomicPtr<Node>>()` bytes.

**Comment by accelsao** [comment]
> @accelsao I think I might find the root cause of UB:
> In previous implementation, when allocating a `Node`, we init the `next_nodes` by calling `ptr::write_bytes`
> 
> ```rust
> ptr::write_bytes(&mut (*p).next_nodes, 0, height);
> ```
> 
> which writes `height` * `size_of::<[AtomicPtr<Node>; MAX_HEIGHT]>()` bytes. Just a huge mistake 😂.
> 
> Instead, we should use:
> 
> ```rust
> ptr::write_bytes((&mut (*p)).next_nodes.as_mut_ptr(), 0, height);
> ```
> 
> which correctly writes `height` * `size_of::<AtomicPtr<Node>>()` bytes.
> 
Cool !

> Is it OK to force-push my fixed patch to this PR？ It seems you've added two commits.

OK

**Comment by accelsao** [comment]
how do you find ub, from test?

**Comment by accelsao** [comment]
current failures:
```
    db::tests::test_get_from_immutable_layer
    db::tests::test_minor_compactions_happend
    db::tests::test_recover_with_large_log
```

It seems they are independent of this PR.

**Comment by Fullstop000** [comment]
> how do you find ub, from test?

`AddressSanitizer` provides some clues about invalid memory ref when dropping `Node`  so I checked allocated bytes and found the size of `next_nodes`  is not as expected

> current failures:
> 
> ```
>     db::tests::test_get_from_immutable_layer
>     db::tests::test_minor_compactions_happend
>     db::tests::test_recover_with_large_log
> ```
> 
> It seems they are independent of this PR.

I'm investigating these ut failures

**Comment by Fullstop000** [comment]
Currently, `memory_used` is accumulated with the content length of the key even if they are not part of arena allocated bytes to stay consistent with previous behavior.
@accelsao PTAL

**Pull request merged**
